services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: mysql-keycloak
      # KC_DB_URL_PORT: 3306
      DB_USER: keycloak
      DB_PASSWORD: password
      # KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      # KC_PROXY: edge
    ports:
      - 8181:8080
    depends_on:
      - mysql-keycloak
    volumes:
      - ./docker/data/keycloak/realms/:/opt/keycloak/data/import/
  mysql-keycloak:
    container_name: mysql-keycloak
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    # ports:
    #   - 3308:3306
    volumes:
      - ./docker/data/mysql-keycloak/data:/var/lib/mysql

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3101:3100"

  prometheus:
    image: prom/prometheus:v2.46.0
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'

  tempo:
    image: grafana/tempo:2.2.2
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/config/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/data/tempo:/tmp/tempo
    ports:
      - "3110:3100"  # Tempo
      - "9411:9411" # zipkin
  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    volumes:
      - ./docker/config/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3001:3000"