# Reference: https://github.com/Huachao/vscode-restclient


POST http://localhost:8081/api/order HTTP/1.1
Content-Type: application/json

{
  "skuCode": "iphone_13",
  "price": 100.00,
  "quantity": 2
}

###

GET http://localhost:8081/api/order HTTP/1.1


###

GET http://localhost:8080/api/product HTTP/1.1

###




GET http://localhost:8082/api/inventory?skuCode=iphone_13&quantity=2 HTTP/1.1

###



GET http://localhost:8082/api/inventory?skuCode=iphone_13&quantity=200 HTTP/1.1

###

